# Generated by Django 5.1.5 on 2025-01-20 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esc', models.CharField(choices=[('E11', 'Е1-1 42422353'), ('E12', 'Е1-2 42422354'), ('E13', 'Е1-3 42422355'), ('E14', 'Е1-4 42422356'), ('E15', 'Е1-5 42422357'), ('E16', 'Е1-6 42422358'), ('E21', 'Е2-1 42422367'), ('E22', 'Е2-2 42422368'), ('E23', 'Е2-3 42422369'), ('E24', 'Е2-4 42422370'), ('E25', 'Е2-5 42422371'), ('E26', 'Е2-6 42422372'), ('E31', 'Е3-1 42422386'), ('E32', 'Е3-2 42422387'), ('E33', 'Е3-3 42422388'), ('E34', 'Е3-4 42422389'), ('E35', 'Е3-5 42422390'), ('E36', 'Е3-6 42422391'), ('E41', 'Е4-1 42422399'), ('E42', 'Е4-2 42422400'), ('E43', 'Е4-3 42422401'), ('E44', 'Е4-4 42422402'), ('E45', 'Е4-5 42422403'), ('E46', 'Е4-6 42422404'), ('E51', 'Е5-1 42422412'), ('E52', 'Е5-2 42422413'), ('E53', 'Е5-3 42422414'), ('E54', 'Е5-4 42422415'), ('E55', 'Е5-5 42422416'), ('E56', 'Е5-6 42422417'), ('E61', 'Е6-1 42422419'), ('E62', 'Е6-2 42422420'), ('E63', 'Е6-3 42422421'), ('E64', 'Е6-4 42422422'), ('E71', 'Е7-1 42422424'), ('E72', 'Е7-2 42422425'), ('E73', 'Е7-3 42422426'), ('E74', 'Е7-4 42422427'), ('E81', 'Е8-1 42422429'), ('E82', 'Е8-2 42422430'), ('E91', 'Е9-1 42422431'), ('E92', 'Е9-2 42422432')], default='E11', help_text='Выберите эскалатор', max_length=14, verbose_name='Эскалатор')),
            ],
            options={
                'verbose_name': 'Эскалатор',
                'verbose_name_plural': 'Эскалаторы',
            },
        ),
        migrations.CreateModel(
            name='EscProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=255, verbose_name='Проблема')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проблемы')),
                ('resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('esc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esc.esc', verbose_name='Эскалатор')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
            },
        ),
        migrations.CreateModel(
            name='EscReplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replace', models.CharField(max_length=255, verbose_name='Заменить')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замены')),
                ('resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('esc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esc.esc', verbose_name='Эскалатор')),
            ],
            options={
                'verbose_name': 'Замена',
                'verbose_name_plural': 'Замены',
            },
        ),
        migrations.CreateModel(
            name='EscTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения ТО')),
                ('esc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esc.esc', verbose_name='Эскалатор')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
            },
        ),
    ]
