# Generated by Django 5.1.2 on 2024-10-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifts", "0002_problem_buildings_alter_elevator_elevator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="to",
            name="date",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата проведения ТО"
            ),
        ),
    ]
