# Generated by Django 5.1.2 on 2024-10-21 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itr", "0004_alter_passportsnilsinn_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="passport",
            field=models.OneToOneField(
                blank=True,
                help_text="Выбери паспорт сотрудника",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="passports",
                to="itr.passportsnilsinn",
                verbose_name="Паспорт",
            ),
        ),
    ]
