# Generated by Django 5.1.2 on 2024-10-21 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itr", "0005_alter_employee_passport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="passport",
        ),
        migrations.AddField(
            model_name="employee",
            name="addres_registration",
            field=models.CharField(
                blank=True,
                help_text="Введите адрес регистрации",
                max_length=100,
                null=True,
                verbose_name="Адрес регистрации",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Выберете дату рождения",
                null=True,
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_registration",
            field=models.DateField(
                blank=True,
                help_text="Выберете дату регистрации",
                null=True,
                verbose_name="Дата регистрации",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="inn",
            field=models.CharField(
                blank=True,
                help_text="Введите ИНН в формате 123456789012",
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{12}$", "ИНН должен состоять из 12 цифр."
                    )
                ],
                verbose_name="ИНН",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="issued_by",
            field=models.CharField(
                blank=True,
                help_text="Введите кем выдан паспорт",
                max_length=100,
                null=True,
                verbose_name="Кем выдан",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="issued_when",
            field=models.DateField(
                blank=True,
                help_text="Выберете дату выданы паспорта",
                null=True,
                verbose_name="Когда выдан",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="Введите номер паспорта в формате 123456",
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$", "Номер паспорта должен состоять из 6 цифр."
                    )
                ],
                verbose_name="Номер паспорта",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="place_of_birth",
            field=models.CharField(
                blank=True,
                help_text="Введите место рождения",
                max_length=100,
                null=True,
                verbose_name="Место рождения",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="serial",
            field=models.CharField(
                blank=True,
                help_text="Введите серию паспорта в формате 1234",
                max_length=4,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{4}$", "Серия паспорта должна состоять из 4 цифр."
                    )
                ],
                verbose_name="Серия паспорта",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="snils",
            field=models.CharField(
                blank=True,
                help_text="Введите СНИЛС в формате 123-456-789 00",
                max_length=14,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{3}-\\d{3}-\\d{3} \\d{2}$",
                        "СНИЛС должен быть в формате 123-456-789 00.",
                    )
                ],
                verbose_name="СНИЛС",
            ),
        ),
        migrations.DeleteModel(
            name="PassportSnilsInn",
        ),
    ]
