# Generated by Django 5.1.2 on 2024-10-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itr", "0008_employee_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                help_text="Введите телефон сотрудника в формате +79991234567",
                max_length=13,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
    ]
