# renew_before_expiry = 30 days
version = 2.1.0
archive_dir = /etc/letsencrypt/archive/mer1d1an.ru
cert = /etc/letsencrypt/live/mer1d1an.ru/cert.pem
privkey = /etc/letsencrypt/live/mer1d1an.ru/privkey.pem
chain = /etc/letsencrypt/live/mer1d1an.ru/chain.pem
fullchain = /etc/letsencrypt/live/mer1d1an.ru/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 5ac40618ab810f02908bcbadec54b690
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
